#!/bin/bash
set -euxo pipefail

USERNAME="${_REMOTE_USER:-vscode}"
HOME="/home/$USERNAME"
VERSION="stable"
INSTALL_DOTFILES=${INSTALL_DOTFILES:-true}
DOTFILES_REPOSITORY=${DOTFILES_REPOSITORY:-}
DOTFILES_FOLDER=${DOTFILES_FOLDER:-nvim}

export HOME USERNAME VERSION INSTALL_DOTFILES DOTFILES_REPOSITORY DOTFILES_FOLDER
../neovim/install.sh
../cli-oxided/install.sh
